// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/proto/example.proto

package hoge

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Get struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Get) Reset()         { *m = Get{} }
func (m *Get) String() string { return proto.CompactTextString(m) }
func (*Get) ProtoMessage()    {}
func (*Get) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2bc1794c95e3ca, []int{0}
}

func (m *Get) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Get.Unmarshal(m, b)
}
func (m *Get) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Get.Marshal(b, m, deterministic)
}
func (m *Get) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Get.Merge(m, src)
}
func (m *Get) XXX_Size() int {
	return xxx_messageInfo_Get.Size(m)
}
func (m *Get) XXX_DiscardUnknown() {
	xxx_messageInfo_Get.DiscardUnknown(m)
}

var xxx_messageInfo_Get proto.InternalMessageInfo

type Get_Request struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Get_Request) Reset()         { *m = Get_Request{} }
func (m *Get_Request) String() string { return proto.CompactTextString(m) }
func (*Get_Request) ProtoMessage()    {}
func (*Get_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2bc1794c95e3ca, []int{0, 0}
}

func (m *Get_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Get_Request.Unmarshal(m, b)
}
func (m *Get_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Get_Request.Marshal(b, m, deterministic)
}
func (m *Get_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Get_Request.Merge(m, src)
}
func (m *Get_Request) XXX_Size() int {
	return xxx_messageInfo_Get_Request.Size(m)
}
func (m *Get_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Get_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Get_Request proto.InternalMessageInfo

func (m *Get_Request) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Get_Response struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Get_Response) Reset()         { *m = Get_Response{} }
func (m *Get_Response) String() string { return proto.CompactTextString(m) }
func (*Get_Response) ProtoMessage()    {}
func (*Get_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2bc1794c95e3ca, []int{0, 1}
}

func (m *Get_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Get_Response.Unmarshal(m, b)
}
func (m *Get_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Get_Response.Marshal(b, m, deterministic)
}
func (m *Get_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Get_Response.Merge(m, src)
}
func (m *Get_Response) XXX_Size() int {
	return xxx_messageInfo_Get_Response.Size(m)
}
func (m *Get_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Get_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Get_Response proto.InternalMessageInfo

func (m *Get_Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Post struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2bc1794c95e3ca, []int{1}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

type Post_Request struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post_Request) Reset()         { *m = Post_Request{} }
func (m *Post_Request) String() string { return proto.CompactTextString(m) }
func (*Post_Request) ProtoMessage()    {}
func (*Post_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2bc1794c95e3ca, []int{1, 0}
}

func (m *Post_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post_Request.Unmarshal(m, b)
}
func (m *Post_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post_Request.Marshal(b, m, deterministic)
}
func (m *Post_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post_Request.Merge(m, src)
}
func (m *Post_Request) XXX_Size() int {
	return xxx_messageInfo_Post_Request.Size(m)
}
func (m *Post_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Post_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Post_Request proto.InternalMessageInfo

func (m *Post_Request) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Post_Request) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Post_Response struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post_Response) Reset()         { *m = Post_Response{} }
func (m *Post_Response) String() string { return proto.CompactTextString(m) }
func (*Post_Response) ProtoMessage()    {}
func (*Post_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2bc1794c95e3ca, []int{1, 1}
}

func (m *Post_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post_Response.Unmarshal(m, b)
}
func (m *Post_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post_Response.Marshal(b, m, deterministic)
}
func (m *Post_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post_Response.Merge(m, src)
}
func (m *Post_Response) XXX_Size() int {
	return xxx_messageInfo_Post_Response.Size(m)
}
func (m *Post_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Post_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Post_Response proto.InternalMessageInfo

func (m *Post_Response) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*Get)(nil), "garupanojissan.grpc.example.example.Get")
	proto.RegisterType((*Get_Request)(nil), "garupanojissan.grpc.example.example.Get.Request")
	proto.RegisterType((*Get_Response)(nil), "garupanojissan.grpc.example.example.Get.Response")
	proto.RegisterType((*Post)(nil), "garupanojissan.grpc.example.example.Post")
	proto.RegisterType((*Post_Request)(nil), "garupanojissan.grpc.example.example.Post.Request")
	proto.RegisterType((*Post_Response)(nil), "garupanojissan.grpc.example.example.Post.Response")
}

func init() { proto.RegisterFile("example/proto/example.proto", fileDescriptor_0d2bc1794c95e3ca) }

var fileDescriptor_0d2bc1794c95e3ca = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xdd, 0x6d, 0xb1, 0x75, 0x10, 0x91, 0x9c, 0x24, 0x05, 0x91, 0xf5, 0xe2, 0xa5, 0x89,
	0xd6, 0x8b, 0x78, 0x2c, 0x48, 0xaf, 0x12, 0x6f, 0xde, 0xd2, 0x75, 0x48, 0xd7, 0x6d, 0x33, 0x71,
	0x93, 0x05, 0xf5, 0x17, 0xfb, 0x33, 0xa4, 0xd9, 0xdd, 0xda, 0x93, 0x74, 0x4f, 0x99, 0x21, 0xef,
	0x7b, 0xf3, 0x86, 0x81, 0x09, 0x7e, 0xea, 0x8d, 0x5b, 0xa3, 0x74, 0x15, 0x05, 0x92, 0x6d, 0x27,
	0x62, 0xc7, 0xae, 0x8d, 0xae, 0x6a, 0xa7, 0x2d, 0xbd, 0x17, 0xde, 0x6b, 0x2b, 0x4c, 0xe5, 0x72,
	0xd1, 0x49, 0xda, 0x37, 0x9b, 0xc3, 0x60, 0x81, 0x81, 0x4f, 0x60, 0xa4, 0xf0, 0xa3, 0x46, 0x1f,
	0xd8, 0x39, 0x0c, 0x4a, 0xfc, 0xba, 0x48, 0xae, 0x92, 0x9b, 0x13, 0xb5, 0x2d, 0xf9, 0x25, 0x8c,
	0x15, 0x7a, 0x47, 0xd6, 0x23, 0x63, 0x30, 0x7c, 0xd3, 0x41, 0xc7, 0xef, 0x53, 0x15, 0xeb, 0xec,
	0x05, 0x86, 0xcf, 0xe4, 0x03, 0x97, 0xff, 0x98, 0xec, 0xc0, 0xf4, 0x0f, 0xe4, 0x7c, 0xcf, 0xf8,
	0x0c, 0x52, 0x2a, 0x23, 0x30, 0x56, 0x29, 0x95, 0xb3, 0x9f, 0x04, 0x46, 0x4f, 0x4d, 0x48, 0xb6,
	0x8e, 0x21, 0xd9, 0xad, 0x38, 0x60, 0x23, 0xb1, 0xc0, 0x20, 0xda, 0x18, 0xfc, 0xae, 0x07, 0xd1,
	0xe4, 0xc8, 0x8e, 0x18, 0x35, 0xeb, 0xb0, 0xc3, 0xe0, 0xad, 0x74, 0x37, 0x6f, 0xd6, 0x07, 0xe9,
	0x06, 0xce, 0x1f, 0x5f, 0x1f, 0x4c, 0x11, 0x56, 0xf5, 0x52, 0xe4, 0xb4, 0x91, 0x7b, 0x0e, 0xda,
	0x36, 0x87, 0xcd, 0xa7, 0x06, 0xed, 0xb4, 0x42, 0x1f, 0x8a, 0x6f, 0xec, 0xae, 0x2c, 0x57, 0x64,
	0x70, 0x79, 0x1c, 0x05, 0xf7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x84, 0xc1, 0x24, 0xb3, 0x0a,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExampleClient is the client API for Example service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExampleClient interface {
	Get(ctx context.Context, in *Get_Request, opts ...grpc.CallOption) (*Get_Response, error)
	Post(ctx context.Context, in *Post_Request, opts ...grpc.CallOption) (*Post_Response, error)
}

type exampleClient struct {
	cc *grpc.ClientConn
}

func NewExampleClient(cc *grpc.ClientConn) ExampleClient {
	return &exampleClient{cc}
}

func (c *exampleClient) Get(ctx context.Context, in *Get_Request, opts ...grpc.CallOption) (*Get_Response, error) {
	out := new(Get_Response)
	err := c.cc.Invoke(ctx, "/garupanojissan.grpc.example.example.Example/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) Post(ctx context.Context, in *Post_Request, opts ...grpc.CallOption) (*Post_Response, error) {
	out := new(Post_Response)
	err := c.cc.Invoke(ctx, "/garupanojissan.grpc.example.example.Example/Post", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleServer is the server API for Example service.
type ExampleServer interface {
	Get(context.Context, *Get_Request) (*Get_Response, error)
	Post(context.Context, *Post_Request) (*Post_Response, error)
}

// UnimplementedExampleServer can be embedded to have forward compatible implementations.
type UnimplementedExampleServer struct {
}

func (*UnimplementedExampleServer) Get(ctx context.Context, req *Get_Request) (*Get_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedExampleServer) Post(ctx context.Context, req *Post_Request) (*Post_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Post not implemented")
}

func RegisterExampleServer(s *grpc.Server, srv ExampleServer) {
	s.RegisterService(&_Example_serviceDesc, srv)
}

func _Example_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Get_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/garupanojissan.grpc.example.example.Example/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).Get(ctx, req.(*Get_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/garupanojissan.grpc.example.example.Example/Post",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).Post(ctx, req.(*Post_Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Example_serviceDesc = grpc.ServiceDesc{
	ServiceName: "garupanojissan.grpc.example.example.Example",
	HandlerType: (*ExampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Example_Get_Handler,
		},
		{
			MethodName: "Post",
			Handler:    _Example_Post_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/proto/example.proto",
}
